[package]
name = "rusty-git-gui"
version = "0.1.0"
authors = ["Arkadiusz Piekarz <piekarzarkadiusz@gmail.com>"]
edition = "2018"

[dependencies]
color-backtrace = { version = "0.3.0", optional = true, features = ["failure-bt"] }
difference = "2.0.0"
dirs = "2.0.2"
failchain = "0.1015.2"
failure = "0.1.6"
gdk = { version = "0.12.0", default-features = false }
git2 = { version = "0.11.0", default-features = false }
glib = "0.9.1"
gtk = { version = "0.8.0", default-features = false, features = ["v3_22"] }
itertools = { version = "0.8.2", default-features = false, features = ["use_std"] }
rust-ini = "0.14.0"

[dev-dependencies]
mocktopus = "0.7.5"
more-asserts = "0.2.1"
pretty_assertions = "0.6.1"
tempfile = "3.1.0"

[features]
use_color_backtrace = ["color-backtrace"]

[profile.release]
lto = true