[package]
name = "rusty-git-gui"
version = "0.1.0"
authors = ["Arkadiusz Piekarz <piekarzarkadiusz@gmail.com>"]
edition = "2018"

[dependencies]
color-backtrace = { version = "0.3.0", default-features = false, optional = true, features = ["failure-bt"] }
difference = { version = "2.0.0", default-features = false }
dirs = { version = "2.0.2", default-features = false }
failchain = { version = "0.1015.2", default-features = false }
failure = { version = "0.1.6", default-features = false }
gdk = { version = "0.12.0", default-features = false }
git2 = { version = "0.11.0", default-features = false }
glib = { version = "0.9.1", default-features = false }
gtk = { version = "0.8.0", default-features = false, features = ["v3_22"] }
itertools = { version = "0.8.2", default-features = false, features = ["use_std"] }
pango = { version = "0.8.0", default-features = false }
rust-ini = { version = "0.14.0", default-features = false }

[dev-dependencies]
mocktopus = { version = "0.7.5", default-features = false }
more-asserts = { version = "0.2.1", default-features = false }
pretty_assertions = { version = "0.6.1", default-features = false }
tempfile = { version = "3.1.0", default-features = false }

[features]
use_color_backtrace = ["color-backtrace"]

[profile.release]
lto = true