cargo-features = ["named-profiles"]

[workspace]
members = ["integration_tests/*"]

[package]
name = "rusty-git-gui"
version = "0.1.0"
authors = ["Arkadiusz Piekarz <piekarzarkadiusz@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = { version = "1.0.28", default-features = false, features = ["std"] }
color-backtrace = { version = "0.3.0", default-features = false, optional = true }
difference = { version = "2.0.0", default-features = false }
dirs = { version = "2.0.2", default-features = false }
gdk = { version = "0.12.1", default-features = false }
git2 = { version = "0.13.4", default-features = false }
glib = { version = "0.9.3", default-features = false }
gtk = { version = "0.8.1", default-features = false, features = ["v3_22"] }
itertools = { version = "0.9.0", default-features = false, features = ["use_std"] }
mimalloc = { version = "0.1.19", default-features = false, optional = true }
pango = { version = "0.8.0", default-features = false }
rust-ini = { version = "0.15.2", default-features = false }

[dev-dependencies]
mocktopus = { version = "0.7.5", default-features = false }

[features]
use_color_backtrace = ["color-backtrace"]
use_mimalloc = ["mimalloc"]

[profile.release]
lto = "thin"

[profile.max-performance]
inherits = "release"
codegen-units = 1
lto = "fat"
panic = "abort"