[package]
name = "rusty-git-gui"
version = "0.1.0"
authors = ["Arkadiusz Piekarz <piekarzarkadiusz@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = { version = "1.0.62", default-features = false, features = ["backtrace", "std"] }
color-backtrace = { version = "0.5.1", default-features = false, optional = true }
dirs = { version = "4.0.0", default-features = false }
git2 = { version = "0.15.0", default-features = false }
gtk = { version = "0.15.5", default-features = false, features = ["v3_22"] }
itertools = { version = "0.10.3", default-features = false, features = ["use_std"] }
regex = "1.6.0"
serde = { version ="1.0.144", default-features = false, features = ["derive"] }
similar = {version = "2.2.0", default-features = false, features = ["text"] }
termcolor = { version = "1.1.3", default-features = false, optional = true }
time = { version = "0.3.13", default-features = false, features = ["formatting", "macros"] }
to_trait = { version = "0.1.1", default-features = false }
toml = { version = "0.5.9", default-features = false }

[dev-dependencies]
gtk-test = {version = "0.15.0", default-features = false }
pretty_assertions = { version = "1.2.1", default-features = false, features = ["std"] }
rusty-fork = { version = "0.3.0", default-features = false }
tempfile = { version = "3.3.0", default-features = false }

[features]
use_color_backtrace = ["color-backtrace", "termcolor"]

[profile.release]
codegen-units = 1
lto = "fat"
