[package]
name = "rusty-git-gui"
version = "0.1.0"
authors = ["Arkadiusz Piekarz <piekarzarkadiusz@gmail.com>"]
edition = "2018"

[dependencies]
cast = "0.2.2"
color-backtrace = "0.1.3"
failchain = "0.1015.2"
failure = "0.1.5"
gio = "0.6.0"
git2 = "0.8"
glib = "0.7.1"
gtk = { version = "0.6.0", features = ["v3_24"] }

[dev-dependencies]
gtk-test = "0.3.0"
tempfile = "3.0.7"