[package]
name = "rusty-git-gui"
version = "0.1.0"
authors = ["Arkadiusz Piekarz <piekarzarkadiusz@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = { version = "1.0.44", default-features = false, features = ["backtrace", "std"] }
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
color-backtrace = { version = "0.5.1", default-features = false, optional = true }
dirs = { version = "4.0.0", default-features = false }
git2 = { version = "0.13.23", default-features = false }
gtk = { version = "0.14.3", default-features = false, features = ["v3_22"] }
itertools = { version = "0.10.1", default-features = false, features = ["use_std"] }
rust-ini = { version = "0.17.0", default-features = false }
similar = {version = "2.1.0", default-features = false, features = ["text"] }
termcolor = { version = "1.1.2", default-features = false, optional = true }

[dev-dependencies]
gtk-test = {version = "0.7.0", default-features = false }
pretty_assertions = { version = "1.0.0", default-features = false, features = ["std"] }
rusty-fork = { version = "0.3.0", default-features = false }
tempfile = { version = "3.2.0", default-features = false }

[features]
use_color_backtrace = ["color-backtrace", "termcolor"]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
