cargo-features = ["named-profiles"]

[package]
name = "rusty-git-gui"
version = "0.1.0"
authors = ["Arkadiusz Piekarz <piekarzarkadiusz@gmail.com>"]
edition = "2018"
resolver = "2"

[dependencies]
anyhow = { version = "1.0.42", default-features = false, features = ["std"] }
color-backtrace = { version = "0.5.1", default-features = false, optional = true }
dirs = { version = "3.0.2", default-features = false }
git2 = { version = "0.13.20", default-features = false }
gtk = { version = "0.14.0", default-features = false, features = ["v3_22"] }
itertools = { version = "0.10.1", default-features = false, features = ["use_std"] }
mimalloc = { version = "0.1.26", default-features = false, optional = true }
rust-ini = { version = "0.17.0", default-features = false }
similar = {version = "1.3.0", default-features = false, features = ["text"] }
termcolor = { version = "1.1.2", default-features = false, optional = true }

[dev-dependencies]
gtk-test = {version = "0.7.0", default-features = false }
mocktopus = { version = "0.7.11", default-features = false }
pretty_assertions = { version = "0.7.2", default-features = false }
rusty-fork = { version = "0.3.0", default-features = false }
tempfile = { version = "3.2.0", default-features = false }

[features]
use_color_backtrace = ["color-backtrace", "termcolor"]
use_mimalloc = ["mimalloc"]

[profile.release]
lto = "thin"

[profile.max-performance]
inherits = "release"
codegen-units = 1
lto = "fat"
panic = "abort"
