mod allow_committing_when_change_is_staged_and_commit_message_is_filled;
mod allow_committing_when_one_of_staged_changes_is_unstaged_and_message_is_filled;
mod commit_staged_changes_given_no_previous_commits;
mod commit_staged_changes_given_one_previous_commit;
mod forbid_committing_after_message_is_cleared;
mod forbid_committing_when_change_is_staged_but_commit_message_is_empty;
mod forbid_committing_when_last_staged_change_is_unstaged_and_message_is_filled;
mod forbid_committing_when_no_changes_are_staged;