mod unstage_deleted_file;
mod unstage_deleted_file_given_it_was_restored;
mod unstage_modified_change_given_unstaged_modified_change_of_same_file;
mod unstage_modified_file;
mod unstage_new_file;
mod unstage_new_file_given_unstaged_modified_change_of_same_file;